# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3881d2884959300bd23afd7f0e3a141ebd99ea3ca34c5a479bf41ecb3e5b33f87aa7c1cebe2a342770ce3b9bc2aa35c074f570ea5bd33b0122566581237ef71e

test:
  secret_key_base: 9fd96721a8e698303351cb0e3affb1fc40c461c9077789076944775972f1fc7b37022194320d9dab96e6b9f6e1a9a82e06d6bd6f1d091ca928052b3885d5d3e7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
